### ISSUE TITLE
Error in using cohesity_job module with protection_source as vcenter 

### ISSUE THREAD

**Issue by cuxtud** [cohesity/ansible-collection#24]
## ❓ cohesity_job module error

```
"msg": "Elements value for option protection_sources is of type <class 'str'> 
and we were unable to convert to dict: dictionary requested, could not parse JSON or key=value"
```

task
```
tasks:
    - name: Add VM to existing Protection Job
      cohesity_job:
        cluster: "{{ lookup('cypher','secret=secret/cohesityHost') }}"
        username: "{{ lookup('cypher','secret=secret/cohesityUser') }}"
        password: "{{ lookup('cypher','secret=secret/cohesityPass') }}"
        state: present
        name: 'Dev-Non-SQL-VMs'
        environment: VMware
        protection_sources: 
          - "{{ lookup('cypher','secret=secret/cohesityVMwareSource') }}"
        protection_policy: 'Dev-Non-SQL-VMs'
        storage_domain: Default
```

In your [example](https://github.com/cohesity/ansible-collection/blob/main/docs/modules/cohesity_job.rst#examples) you have it as a list but it is expecting a dict, what would be the key name for the source?
