### ISSUE TITLE
Add Storage Domain in a multi-tenant environment.

### ISSUE THREAD

**Issue by takanoshota** [cohesity/ansible-collection#25]
## 🚀 Feature Request

For users who use cohesity in a multi-tenant environment, can you add module to add storage domains?
It is best to set quotas to every tenant.

## Example or reference 

I'd like to add module like below.

```
- name: Add Storage Domain to Cohesity DataProtect
  hosts: cohesity_cluster
  tasks:
    - name: Add Storage Domain
      cohesity_storage_domain:
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        cluster: "{{ cohesity_cluster }}"
        state: present
        duplicate: true
        compression: true
        logical_quota: 10Gi
        pyhsical_quota: 10Gi
```
