### ISSUE TITLE
Documentation for Cohesity Refresh Protection Source Issue #22

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#26]
## 📚 Documentation

Where are the playbooks and documentation on how to refresh the different types of sources?  related to Issue #22 that was closed.  I was hoping for a script to just put in the source name or a list of source names.

**Comment by naveena-maplelabs** [comment]
@amhaats1, Can you please check the playbooks now.
https://github.com/cohesity/ansible-collection/tree/main/playbooks/physical-workflow
https://github.com/cohesity/ansible-collection/tree/main/playbooks/oracle-workflow

**Comment by amhaats1** [comment]
Thank you, are there any plans to have a refresh source script built in for the UDA workflow or do I need to open another issue for that request?

**Comment by naveena-maplelabs** [comment]
@amhaats1, To refresh a Uda source, please add new field **refresh** and set to true.
```
cohesity_uda_source:
    server: cohesity.lab
    username: admin
    password: password
    endpoint: myvcenter.host.lab
    state: present
    refresh: true
```
