### ISSUE TITLE
SMB NAS Backup Source won't work with active directory domain credentials

### ISSUE THREAD

**Issue by ptp-sysadmin** [cohesity/ansible-collection#44]
## 🐛 Bug Report

We're trying to use the NAS SMB source task to create a NAS source on the cohesity. 

Our NAS is active directory joined and thus the NAS username needs to be entered in domain\username or username@domain format to work. 

When we attempt to run the following playbook task:

```
- name: Configure Cohesity Protection Sources: SMB
  cohesity_source:
    cluster: "{{ cohesity_server }}"
    username: "{{ cohesity_username }}"
    password: "{{ cohesity_password }}"
    validate_certs: "{{ validate_certs }}"
    state: present
    endpoint: "{{ item }}"
    environment: "GenericNas"
    nas_protocol: "SMB"
    nas_username: ourdomain\backup
    nas_password: "{{ fileserver_password }}"
    skip_validation: "true"
    nas_type: "Host"
  loop: "{{ smb_shares }}"
  loop_control:
    label: "{{ item }}"
```

If I set `skip_validation` to `false` the protection source fails to create.

If I set `skip_validation` to `true` then the source is created but the username in the source is `\ourdomain\backup`. Note the extra backslash prefixing the username. 

I also tried with backup@ourdomain.local but that produces an error about the `@` in the username being a reserved/special character:

failed: [control] (item=\\files\test) => {"ansible_loop_var": "item", "changed": false, "error_class": "bytes", "error_details": "b'{\"errorCode\":\"KInvalidRequest\",\"message\":\"The username contains a few invalid characters: \\\\\"/@+=;,?*%&<>[]:|\"}\\n'", "item": "\\\\files\\test", "msg": "Unexpected error caused while managing the Cohesity Module."}

## To Reproduce

1. Setup a windows file server connected to active directory. Grant a active directory user access to the SMB share.
2. Create an ansible playbook that uses the cohesity_source task. And set the nas_username value to either domain\username or username@domain

## Expected behavior

The cohesity source would get created regardless of if we use domain\username or username@domain formats. 

## Actual Behavior

It doesn't work in either situation.

![image](https://github.com/cohesity/ansible-collection/assets/84792323/0063f842-9d9c-4267-90ac-907d5612a389)
