### ISSUE TITLE
Windows Agent Installation broken 

### ISSUE THREAD

**Issue by killerclaffey** [cohesity/ansible-collection#48]
## 🐛 Bug Report

Getting 400 errors when trying to install windows agent with ansible collection 
```
TASK [data-protection : Include system specific variables] *********************
ok: [win2019]

TASK [data-protection : Install cohesity agent on Windows] *********************
fatal: [win2019]: FAILED! => {"changed": false, "command": null, "msg": "The remote server returned an error: (400) Bad Request.", "step": "Failed while trying to get a new Access Token", "uri": "https://cohesitycluster.redacted.com/irisservices/api/v1/public/accessTokens"}
...ignoring
``` 

However the linux agent is installing with absolutely 0 issue

```
TASK [data-protection : Install the current version of the agent on Linux] *****
ok: [ubu22]
ok: [sles15]
ok: [rhel8]
```

Versioning and requirement info
Package                   Version
------------------------- -----------
ansible-compat            24.6.0
ansible-core              2.15.12
cohesity_management_sdk   1.10.1
requests                  2.32.3
requests-ntlm             1.2.0

> python --version
Python 3.9.19

Cohesity Cluster software version:: 6.8.1_u7_release-20231213_41094bba

## To Reproduce

(Write your steps here:)

1. Try running windows agent installation playbook you will see its currently broken
```yml
- name: Install cohesity agent on Windows
  cohesity.dataprotect.cohesity_win_agent:
    cluster: '{{ cohesity_target }}'
    username: '{{ cohesity_admin }}'
    password: '{{ cohesity_password }}'
    download_uri: '{{ cohesity_win_url }}'
    state: present
    install_type: allcbt
    validate_certs: false
    preserve_settings: false
    
    ```
2. Recieve 400 error from cohesity cluster on Virtual Edtion Version 6.8.1_u7_release-20231213_41094bba

## Expected behavior

Install the agent on the windows 2019 host

## Actual Behavior

400 error trying to use api
